version: '3.8'
services:
  wordpress:
    image: wordpress:6.4-php8.2-apache
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
    volumes:
      - ./_wordpress-org:/var/www/html
      - ./:/var/www/html/wp-content/themes/aegis
      - wp_uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${WORDPRESS_DB_USER:-wordpress}
      PMA_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MYSQL_USER: ${WORDPRESS_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-wordpress}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  node:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sleep infinity
    tty: true
    restart: unless-stopped

volumes:
  db_data:
  wp_uploads:
