name: Accessibility Report
description: Report an accessibility issue related to the Aegis WordPress Block Theme.
labels:
  - '[Type] Accessibility'
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an accessibility issue! Your feedback helps us ensure the Aegis WordPress Block Theme is usable and inclusive for everyone. Please provide as much detail as possible to help us understand and resolve the issue.
  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a detailed description of the accessibility issue. Include what you expected to happen and what actually happened.
    validations:
      required: true
  - type: textarea
    id: elements
    attributes:
      label: Affected Elements
      description: List any specific elements, components, or blocks where the accessibility issue occurs.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide the steps needed to reproduce the accessibility issue.
      placeholder: |
        1. Go to '...'
        2. Use '...' assistive technology (e.g., screen reader, keyboard-only navigation)
        3. Observe the '...' behavior
    validations:
      required: true
  - type: textarea
    id: standards
    attributes:
      label: Accessibility Standards Affected
      description: Specify which accessibility standards or guidelines are not being met (e.g., WCAG 2.1, ARIA roles, keyboard navigation).
      placeholder: |
        Example: WCAG 2.1 AA - 1.3.1 Info and Relationships
    validations:
      required: false
  - type: textarea
    id: media
    attributes:
      label: Screenshots or Videos
      description: Provide screenshots, screen recordings, or videos demonstrating the accessibility issue.
    validations:
      required: false

  - type: group
    id: wordpress-environment
    attributes:
      label: WordPress Environment
    body:
      - type: input
        id: wp-version
        attributes:
          label: WordPress Version
          description: What version of WordPress are you running?
        validations:
          required: true
      - type: input
        id: php-version
        attributes:
          label: PHP Version
          description: What version of PHP are you running?
        validations:
          required: true
      - type: input
        id: theme-version
        attributes:
          label: Theme Version
          description: What version of the Aegis theme are you using?
        validations:
          required: true
      - type: textarea
        id: active-plugins
        attributes:
          label: Active Plugins
          description: Please provide a list of all active plugins.
        validations:
          required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Provide details about your environment, including the assistive technology used (e.g., screen reader, keyboard-only navigation), browser version, and operating system.
      placeholder: |
        Assistive technology: 
    validations:
      required: false
