name: Bug report
description: Create a report to help us improve
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for helping us improve the Aegis WordPress Block Theme!**
        Please fill out the following to help us reproduce and fix the bug.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem (if applicable).
    validations:
      required: false
  - type: input
    id: desktop
    attributes:
      label: Desktop (please complete the following information)
      description: OS, Browser, and Version
      placeholder: |
        OS: [e.g. Windows, macOS]
        Browser: [e.g. Chrome, Safari]
        Version: [e.g. 22]
    validations:
      required: false
  - type: input
    id: smartphone
    attributes:
      label: Smartphone (please complete the following information)
      description: Device, OS, Browser, and Version
      placeholder: |
        Device: [e.g. iPhone6]
        OS: [e.g. iOS8.1]
        Browser: [e.g. Safari]
        Version: [e.g. 22]
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
