name: Feature request
description: Suggest an idea for the Aegis WordPress Block Theme
labels:
  - enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for suggesting an idea to improve the Aegis WordPress Block Theme!**
        Aegis prioritizes performance and vanilla standards. Please describe your suggestion below.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: What part of the theme does this primarily affect?
      options:
        - Block Pattern (Layout)
        - Global Styles (theme.json / Design Tokens)
        - Template / Parts
        - Core Functionality (PHP / JS)
        - Documentation
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false