name: Support/Question
description: Ask a question or request support for the Aegis WordPress Block Theme
labels:
  - question
  - support
  - triage
body:
  - type: markdown
    attributes:
      value: |
        **Need help or have a question?**
        Before opening a support request, please check our [Documentation](https://github.com/aegiswp/theme/wiki) and [Discussions](https://github.com/aegiswp/theme/discussions).
  - type: textarea
    id: help
    attributes:
      label: What do you need help with?
      description: A clear and concise description of your question or the support you need.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps you've tried
      description: Describe what you have already tried or researched (e.g., "I checked the Wiki and tried disabling plugins").
    validations:
      required: false
  - type: textarea
    id: docs
    attributes:
      label: Relevant documentation or links
      description: Links to documentation or forum posts you've already reviewed.
    validations:
      required: false

  - type: group
    id: environment
    attributes:
      label: WordPress Environment (Optional)
    body:
      - type: input
        id: wp-version
        attributes:
          label: WordPress Version
        validations:
          required: false
      - type: input
        id: theme-version
        attributes:
          label: Theme Version
        validations:
          required: false
      - type: textarea
        id: active-plugins
        attributes:
          label: Active Plugins
        validations:
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any screenshots, code snippets, or details that might help us assist you.
    validations:
      required: false