name: Linting and Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx

  php_code_quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install PHP Dependencies
      run: composer install

    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=phpcs.xml

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --configuration=phpstan.neon.dist
